### PR TITLE
A few text tweaks.

### PR DESCRIPTION
**Pull request by Ravendwyr**
Just a handful of tweaks I made to things I spotted.

### CODE REVIEW

**Comment by tustin2121** [comment]
I legit didn't even see this come in, but I happened to see the email about it being closed. I can add a few of these changes.

**Comment by Ravendwyr** [comment]
No worries. I needed to refresh my fork anyway. :)

**Comment by Ravendwyr** [comment]
Sorry about any trouble. I forgot that deleting forks automatically closed PRs.

**Comment by tustin2121** [comment]
It's fine. The trouble here with the multiple commits and force pushing just now was with github's tool doing stupid things. You're all good.

**Pull request closed without merging**
